// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: teste.proto

package com.example.grpc.server.grpcserver;

public interface PingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.PingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ping = 1;</code>
   * @return The ping.
   */
  java.lang.String getPing();
  /**
   * <code>string ping = 1;</code>
   * @return The bytes for ping.
   */
  com.google.protobuf.ByteString
      getPingBytes();
}
