// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: teste.proto

package com.example.grpc.server.grpcserver;

public interface PongResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.PongResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pong = 1;</code>
   * @return The pong.
   */
  java.lang.String getPong();
  /**
   * <code>string pong = 1;</code>
   * @return The bytes for pong.
   */
  com.google.protobuf.ByteString
      getPongBytes();
}
