// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculationImc.proto

package com.philips.api.calculation;

public interface CalculationImcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculationImc.CalculationImcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double result = 1;</code>
   * @return The result.
   */
  double getResult();

  /**
   * <code>string Message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string Message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
