// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculationImc.proto

package com.philips.api.calculation;

public interface CalculationImcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculationImc.CalculationImcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.calculationImc.CalculationImc calc = 1;</code>
   * @return Whether the calc field is set.
   */
  boolean hasCalc();
  /**
   * <code>.calculationImc.CalculationImc calc = 1;</code>
   * @return The calc.
   */
  com.philips.api.calculation.CalculationImc getCalc();
  /**
   * <code>.calculationImc.CalculationImc calc = 1;</code>
   */
  com.philips.api.calculation.CalculationImcOrBuilder getCalcOrBuilder();
}
