// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculationImc.proto

package com.philips.api.calculation;

public interface CalculationImcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculationImc.CalculationImc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double height = 1;</code>
   * @return The height.
   */
  double getHeight();

  /**
   * <code>double weight = 2;</code>
   * @return The weight.
   */
  double getWeight();
}
