// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculationImc.proto

package com.philips.api.calculation;

public final class CalculationImcOuterClass {
  private CalculationImcOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calculationImc_CalculationImc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calculationImc_CalculationImc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calculationImc_CalculationImcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calculationImc_CalculationImcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calculationImc_CalculationImcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calculationImc_CalculationImcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024calculationImc.proto\022\016calculationImc\"0" +
      "\n\016CalculationImc\022\016\n\006height\030\001 \001(\001\022\016\n\006weig" +
      "ht\030\002 \001(\001\"E\n\025CalculationImcRequest\022,\n\004cal" +
      "c\030\001 \001(\0132\036.calculationImc.CalculationImc\"" +
      "9\n\026CalculationImcResponse\022\016\n\006result\030\001 \001(" +
      "\001\022\017\n\007Message\030\002 \001(\t2w\n\025CalculationImcServ" +
      "ice\022^\n\013Calculation\022%.calculationImc.Calc" +
      "ulationImcRequest\032&.calculationImc.Calcu" +
      "lationImcResponse\"\000B\037\n\033com.philips.api.c" +
      "alculationP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_calculationImc_CalculationImc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_calculationImc_CalculationImc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calculationImc_CalculationImc_descriptor,
        new java.lang.String[] { "Height", "Weight", });
    internal_static_calculationImc_CalculationImcRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_calculationImc_CalculationImcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calculationImc_CalculationImcRequest_descriptor,
        new java.lang.String[] { "Calc", });
    internal_static_calculationImc_CalculationImcResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_calculationImc_CalculationImcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calculationImc_CalculationImcResponse_descriptor,
        new java.lang.String[] { "Result", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
