// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculationImc.proto

package com.philips.api.calculation;

/**
 * Protobuf type {@code calculationImc.CalculationImcRequest}
 */
public  final class CalculationImcRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:calculationImc.CalculationImcRequest)
    CalculationImcRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CalculationImcRequest.newBuilder() to construct.
  private CalculationImcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CalculationImcRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CalculationImcRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CalculationImcRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.philips.api.calculation.CalculationImc.Builder subBuilder = null;
            if (calc_ != null) {
              subBuilder = calc_.toBuilder();
            }
            calc_ = input.readMessage(com.philips.api.calculation.CalculationImc.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(calc_);
              calc_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.philips.api.calculation.CalculationImcOuterClass.internal_static_calculationImc_CalculationImcRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.philips.api.calculation.CalculationImcOuterClass.internal_static_calculationImc_CalculationImcRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.philips.api.calculation.CalculationImcRequest.class, com.philips.api.calculation.CalculationImcRequest.Builder.class);
  }

  public static final int CALC_FIELD_NUMBER = 1;
  private com.philips.api.calculation.CalculationImc calc_;
  /**
   * <code>.calculationImc.CalculationImc calc = 1;</code>
   * @return Whether the calc field is set.
   */
  public boolean hasCalc() {
    return calc_ != null;
  }
  /**
   * <code>.calculationImc.CalculationImc calc = 1;</code>
   * @return The calc.
   */
  public com.philips.api.calculation.CalculationImc getCalc() {
    return calc_ == null ? com.philips.api.calculation.CalculationImc.getDefaultInstance() : calc_;
  }
  /**
   * <code>.calculationImc.CalculationImc calc = 1;</code>
   */
  public com.philips.api.calculation.CalculationImcOrBuilder getCalcOrBuilder() {
    return getCalc();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (calc_ != null) {
      output.writeMessage(1, getCalc());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (calc_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCalc());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.philips.api.calculation.CalculationImcRequest)) {
      return super.equals(obj);
    }
    com.philips.api.calculation.CalculationImcRequest other = (com.philips.api.calculation.CalculationImcRequest) obj;

    if (hasCalc() != other.hasCalc()) return false;
    if (hasCalc()) {
      if (!getCalc()
          .equals(other.getCalc())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCalc()) {
      hash = (37 * hash) + CALC_FIELD_NUMBER;
      hash = (53 * hash) + getCalc().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.philips.api.calculation.CalculationImcRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.philips.api.calculation.CalculationImcRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.philips.api.calculation.CalculationImcRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.philips.api.calculation.CalculationImcRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.philips.api.calculation.CalculationImcRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.philips.api.calculation.CalculationImcRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.philips.api.calculation.CalculationImcRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.philips.api.calculation.CalculationImcRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.philips.api.calculation.CalculationImcRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.philips.api.calculation.CalculationImcRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.philips.api.calculation.CalculationImcRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.philips.api.calculation.CalculationImcRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.philips.api.calculation.CalculationImcRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code calculationImc.CalculationImcRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:calculationImc.CalculationImcRequest)
      com.philips.api.calculation.CalculationImcRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.philips.api.calculation.CalculationImcOuterClass.internal_static_calculationImc_CalculationImcRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.philips.api.calculation.CalculationImcOuterClass.internal_static_calculationImc_CalculationImcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.philips.api.calculation.CalculationImcRequest.class, com.philips.api.calculation.CalculationImcRequest.Builder.class);
    }

    // Construct using com.philips.api.calculation.CalculationImcRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (calcBuilder_ == null) {
        calc_ = null;
      } else {
        calc_ = null;
        calcBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.philips.api.calculation.CalculationImcOuterClass.internal_static_calculationImc_CalculationImcRequest_descriptor;
    }

    @java.lang.Override
    public com.philips.api.calculation.CalculationImcRequest getDefaultInstanceForType() {
      return com.philips.api.calculation.CalculationImcRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.philips.api.calculation.CalculationImcRequest build() {
      com.philips.api.calculation.CalculationImcRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.philips.api.calculation.CalculationImcRequest buildPartial() {
      com.philips.api.calculation.CalculationImcRequest result = new com.philips.api.calculation.CalculationImcRequest(this);
      if (calcBuilder_ == null) {
        result.calc_ = calc_;
      } else {
        result.calc_ = calcBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.philips.api.calculation.CalculationImcRequest) {
        return mergeFrom((com.philips.api.calculation.CalculationImcRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.philips.api.calculation.CalculationImcRequest other) {
      if (other == com.philips.api.calculation.CalculationImcRequest.getDefaultInstance()) return this;
      if (other.hasCalc()) {
        mergeCalc(other.getCalc());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.philips.api.calculation.CalculationImcRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.philips.api.calculation.CalculationImcRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.philips.api.calculation.CalculationImc calc_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.philips.api.calculation.CalculationImc, com.philips.api.calculation.CalculationImc.Builder, com.philips.api.calculation.CalculationImcOrBuilder> calcBuilder_;
    /**
     * <code>.calculationImc.CalculationImc calc = 1;</code>
     * @return Whether the calc field is set.
     */
    public boolean hasCalc() {
      return calcBuilder_ != null || calc_ != null;
    }
    /**
     * <code>.calculationImc.CalculationImc calc = 1;</code>
     * @return The calc.
     */
    public com.philips.api.calculation.CalculationImc getCalc() {
      if (calcBuilder_ == null) {
        return calc_ == null ? com.philips.api.calculation.CalculationImc.getDefaultInstance() : calc_;
      } else {
        return calcBuilder_.getMessage();
      }
    }
    /**
     * <code>.calculationImc.CalculationImc calc = 1;</code>
     */
    public Builder setCalc(com.philips.api.calculation.CalculationImc value) {
      if (calcBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        calc_ = value;
        onChanged();
      } else {
        calcBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.calculationImc.CalculationImc calc = 1;</code>
     */
    public Builder setCalc(
        com.philips.api.calculation.CalculationImc.Builder builderForValue) {
      if (calcBuilder_ == null) {
        calc_ = builderForValue.build();
        onChanged();
      } else {
        calcBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.calculationImc.CalculationImc calc = 1;</code>
     */
    public Builder mergeCalc(com.philips.api.calculation.CalculationImc value) {
      if (calcBuilder_ == null) {
        if (calc_ != null) {
          calc_ =
            com.philips.api.calculation.CalculationImc.newBuilder(calc_).mergeFrom(value).buildPartial();
        } else {
          calc_ = value;
        }
        onChanged();
      } else {
        calcBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.calculationImc.CalculationImc calc = 1;</code>
     */
    public Builder clearCalc() {
      if (calcBuilder_ == null) {
        calc_ = null;
        onChanged();
      } else {
        calc_ = null;
        calcBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.calculationImc.CalculationImc calc = 1;</code>
     */
    public com.philips.api.calculation.CalculationImc.Builder getCalcBuilder() {
      
      onChanged();
      return getCalcFieldBuilder().getBuilder();
    }
    /**
     * <code>.calculationImc.CalculationImc calc = 1;</code>
     */
    public com.philips.api.calculation.CalculationImcOrBuilder getCalcOrBuilder() {
      if (calcBuilder_ != null) {
        return calcBuilder_.getMessageOrBuilder();
      } else {
        return calc_ == null ?
            com.philips.api.calculation.CalculationImc.getDefaultInstance() : calc_;
      }
    }
    /**
     * <code>.calculationImc.CalculationImc calc = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.philips.api.calculation.CalculationImc, com.philips.api.calculation.CalculationImc.Builder, com.philips.api.calculation.CalculationImcOrBuilder> 
        getCalcFieldBuilder() {
      if (calcBuilder_ == null) {
        calcBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.philips.api.calculation.CalculationImc, com.philips.api.calculation.CalculationImc.Builder, com.philips.api.calculation.CalculationImcOrBuilder>(
                getCalc(),
                getParentForChildren(),
                isClean());
        calc_ = null;
      }
      return calcBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:calculationImc.CalculationImcRequest)
  }

  // @@protoc_insertion_point(class_scope:calculationImc.CalculationImcRequest)
  private static final com.philips.api.calculation.CalculationImcRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.philips.api.calculation.CalculationImcRequest();
  }

  public static com.philips.api.calculation.CalculationImcRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CalculationImcRequest>
      PARSER = new com.google.protobuf.AbstractParser<CalculationImcRequest>() {
    @java.lang.Override
    public CalculationImcRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CalculationImcRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CalculationImcRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CalculationImcRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.philips.api.calculation.CalculationImcRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

