// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dummy.proto

package com.philips.api.calculation;

public interface DummyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dummy.DummyMessage)
    com.google.protobuf.MessageOrBuilder {
}
